export { InvalidProfileSpecError } from './errors.js';
export {
  PROFILE_SPEC_MIGRATIONS,
  migrateProfileSpec,
  type ProfileSpecMigration,
  type ProfileSpecMigrationResult,
} from './migration.js';
export { profileSpecJsonSchema } from './schema.js';
export {
  canonicalProfileSpecValue,
  cloneProfileSpec,
  createProfileSpecRevision,
  parseProfileSpec,
  serializeProfileSpec,
  type CreateProfileSpecRevisionOptions,
  type ParseProfileSpecResult,
  type SerializeProfileSpecOptions,
} from './serialization.js';
export { PROFILE_SPEC_SCHEMA_VERSION } from './types.js';
export { validateProfileSpec } from './validation.js';
export type {
  ProfileSpecValidationResult,
  ValidationIssue,
  ValidationSeverity,
} from './validation.js';
export type {
  AutoDetectProfile,
  BypassCondition,
  BypassEntry,
  BuiltInProfileAppearance,
  BuiltInRouteTarget,
  Condition,
  FalseCondition,
  FixedProfile,
  HostLevelsCondition,
  HostRegexCondition,
  HostWildcardCondition,
  InterfaceSettings,
  IpCondition,
  JsonPrimitive,
  JsonValue,
  KeywordCondition,
  LegacyMetadata,
  LiteralHeaderValue,
  PacProfile,
  PacSource,
  ProfileRouteTarget,
  ProfileSpec,
  ProfileSpecSchemaVersion,
  ProfileSpecSettings,
  ProxyCredentialReference,
  ProxyEndpoint,
  QuickSwitchSettings,
  RevisionMetadata,
  RuleListFormat,
  RuleListProfile,
  RuleSource,
  RuleSourceHeader,
  RuleSourceLocation,
  SecretHeaderValue,
  StartupSettings,
  SwitchProfile,
  SwitchRule,
  SyncSettings,
  TimeCondition,
  TrueCondition,
  UrlRegexCondition,
  UrlWildcardCondition,
  UserProfile,
  Weekday,
  WeekdayCondition,
} from './types.js';
