import { readFile } from 'node:fs/promises';

import { describe, expect, it } from 'vitest';

import { exportZeroOmegaBackup, importZeroOmegaBackup } from './index.js';

const FIXTURE_ROOT = new URL('../../../fixtures/zeroomega-v2/', import.meta.url);

async function fixture(name: string): Promise<string> {
  return readFile(new URL(name, FIXTURE_ROOT), 'utf8');
}

const context = {
  createdAt: '2026-07-28T00:00:00.000Z',
  documentId: 'document-export-test',
  revisionId: 'revision-export-test',
  deviceId: 'device-export-test',
} as const;

function successfulImport(source: string) {
  const result = importZeroOmegaBackup(source, context);
  if (!result.ok) throw new Error(JSON.stringify(result.report, null, 2));
  expect(result.ok).toBe(true);
  return result;
}

describe('ZeroOmega schema-v2 exporter', () => {
  it('round-trips the representative original profile fixture through plain JSON', async () => {
    const first = successfulImport(await fixture('minimal-profile-types.json'));
    const exported = exportZeroOmegaBackup(first.candidate, {
      createdAt: '2026-07-28T01:02:03.004Z',
    });
    expect(exported.ok).toBe(true);
    if (!exported.ok) throw new Error(JSON.stringify(exported.issues, null, 2));

    expect(exported.filename).toBe('ZeroOmegaOptions-2026-07-28T01:02:03.004Z.bak');
    expect(exported.mimeType).toBe('text/plain;charset=utf-8');
    expect(exported.content).toBe(JSON.stringify(exported.options));
    expect(JSON.parse(exported.content)).toMatchObject({
      schemaVersion: 2,
      '-startupProfileName': 'switch',
      '-quickSwitchProfiles': ['switch', 'fixed', 'direct'],
      '+fixed': { profileType: 'FixedProfile' },
      '+switch': { profileType: 'SwitchProfile' },
      '+virtual': { profileType: 'VirtualProfile' },
      '+rule-switchy': { profileType: 'RuleListProfile', format: 'Switchy' },
    });

    const second = successfulImport(exported.content);
    expect(second.candidate).toEqual(first.candidate);
  });

  it('round-trips a backup generated by the pinned original v3.5.0 module', async () => {
    const first = successfulImport(await fixture('original-default-v3.5.0.bak'));
    const exported = exportZeroOmegaBackup(first.candidate, {
      createdAt: context.createdAt,
    });
    expect(exported.ok).toBe(true);
    if (!exported.ok) throw new Error(JSON.stringify(exported.issues, null, 2));
    const second = successfulImport(exported.content);
    expect(second.candidate).toEqual(first.candidate);
  });

  it('omits proxy credentials and sensitive headers from ordinary backups', async () => {
    const imported = successfulImport(await fixture('credentials-and-headers.redacted.json'));
    const exported = exportZeroOmegaBackup(imported.candidate, {
      createdAt: context.createdAt,
    });
    expect(exported.ok).toBe(true);
    if (!exported.ok) throw new Error(JSON.stringify(exported.issues, null, 2));

    expect(exported.omittedSecretCount).toBeGreaterThan(0);
    expect(exported.issues.map((entry) => entry.code)).toEqual(
      expect.arrayContaining(['secret.proxy-credential-omitted', 'secret.request-header-omitted']),
    );
    expect(exported.content).not.toContain('passwordSecretRef');
    expect(exported.content).not.toContain('secretRef');
    expect(exported.content).not.toContain('<redacted>');
    expect(exported.content).not.toContain('Authorization');
  });

  it('preserves Nex-only disabled, regex-flag, PAC/Auto fallback, and per-source interval state', () => {
    const imported = successfulImport(
      JSON.stringify({
        schemaVersion: 2,
        '-startupProfileName': 'switch',
        '-downloadInterval': 1440,
        '+fixed': {
          name: 'fixed',
          profileType: 'FixedProfile',
          fallbackProxy: { scheme: 'http', host: 'proxy.test', port: 8080 },
          bypassList: [
            {
              conditionType: 'BypassCondition',
              pattern: 'disabled.test',
              enabled: false,
              note: 'disabled bypass',
            },
          ],
        },
        '+pac': {
          name: 'pac',
          profileType: 'PacProfile',
          pacScript: 'function FindProxyForURL(){return "DIRECT";}',
          fallbackProfileName: 'fixed',
        },
        '+auto': {
          name: 'auto',
          profileType: 'AutoDetectProfile',
          fallbackProfileName: 'fixed',
        },
        '+rules': {
          name: 'rules',
          profileType: 'RuleListProfile',
          format: 'Switchy',
          ruleList: '[SwitchyOmega Conditions]\n@with result\n\n* +direct\n',
          matchProfileName: 'fixed',
          defaultProfileName: 'direct',
          updateIntervalMinutes: 60,
          enabled: false,
        },
        '+switch': {
          name: 'switch',
          profileType: 'SwitchProfile',
          defaultProfileName: 'pac',
          rules: [
            {
              condition: {
                conditionType: 'HostRegexCondition',
                pattern: '^example\\.test$',
                flags: 'i',
              },
              profileName: 'rules',
              enabled: false,
            },
          ],
        },
      }),
    );
    const exported = exportZeroOmegaBackup(imported.candidate, {
      createdAt: context.createdAt,
    });
    expect(exported.ok).toBe(true);
    if (!exported.ok) throw new Error(JSON.stringify(exported.issues, null, 2));
    const second = successfulImport(exported.content);
    expect(second.candidate).toEqual(imported.candidate);
    expect(exported.issues.map((entry) => entry.code)).toEqual(
      expect.arrayContaining([
        'profile.disabled-nex-extension',
        'switch-rule.disabled-nex-extension',
        'condition.regex-flags-nex-extension',
        'pac.fallback-nex-extension',
        'auto-detect.fallback-nex-extension',
        'rule-source.interval-nex-extension',
      ]),
    );
  });
});
